spring.application.name=doubt-solver-backend
server.port=${SERVER_PORT:8081}
spring.datasource.url=jdbc:h2:file:./data/doubts;DB_CLOSE_DELAY=-1;MODE=LEGACY
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.web.resources.static-locations=classpath:/static/,file:./uploads/
